export const API_ROUTES = Object.freeze([
  { id: "accountSession", domain: "account", methods: ["GET"], path: "/api/account/session" },
  { id: "accountSignup", domain: "account", methods: ["POST"], path: "/api/account/signup" },
  { id: "accountLogin", domain: "account", methods: ["POST"], path: "/api/account/login" },
  { id: "accountLogout", domain: "account", methods: ["POST"], path: "/api/account/logout" },
  { id: "health", domain: "dashboard", methods: ["GET"], path: "/api/health" },
  { id: "state", domain: "dashboard", methods: ["GET"], path: "/api/state" },
  { id: "ruleExplain", domain: "policy", methods: ["GET", "POST"], path: "/api/rules/explain" },
  { id: "extensionCheck", domain: "extension", methods: ["GET", "POST"], path: "/api/extension/check" },
  { id: "extensionPairing", domain: "extension", methods: ["GET"], path: "/api/extension/pairing" },
  { id: "extensionRules", domain: "extension", methods: ["GET"], path: "/api/extension/rules" },
  { id: "extensionRulesSync", domain: "extension", methods: ["POST"], path: "/api/extension/rules/sync" },
  { id: "extensionPauseContinue", domain: "extension", methods: ["POST"], path: "/api/extension/pause/continue" },
  { id: "extensionPauseSkip", domain: "extension", methods: ["POST"], path: "/api/extension/pause/skip" },
  { id: "diagnosticExport", domain: "diagnostics", methods: ["GET"], path: "/api/diagnostic/export" },
  { id: "appUpdateStatus", domain: "app", methods: ["GET"], path: "/api/app-update/status" },
  { id: "appUpdateStart", domain: "app", methods: ["POST"], path: "/api/app-update/start" },
  { id: "settings", domain: "settings", methods: ["POST"], path: "/api/settings" },
  { id: "adultBlocklistSettings", domain: "hardening", methods: ["POST"], path: "/api/adult-blocklist/settings" },
  { id: "adultBlocklistRefresh", domain: "hardening", methods: ["POST"], path: "/api/adult-blocklist/refresh" },
  { id: "panicStart", domain: "sessions", methods: ["POST"], path: "/api/panic/start" },
  { id: "protectionLevel", domain: "sessions", methods: ["POST"], path: "/api/protection/level" },
  { id: "keyholder", domain: "protection", methods: ["POST"], path: "/api/keyholder" },
  { id: "distanceKey", domain: "protection", methods: ["POST"], path: "/api/distance-key" },
  { id: "launchAgentInstall", domain: "hardening", methods: ["POST"], path: "/api/hardening/launch-agent/install" },
  { id: "hostsApply", domain: "hardening", methods: ["POST"], path: "/api/hardening/hosts/apply" },
  { id: "safariFilterApply", domain: "hardening", methods: ["POST"], path: "/api/hardening/safari-filter/apply" },
  { id: "clearTamper", domain: "hardening", methods: ["POST"], path: "/api/integrity/clear-tamper" },
  { id: "iosSettings", domain: "devices", methods: ["POST"], path: "/api/devices/ios/settings" },
  { id: "iosAppRemoval", domain: "devices", methods: ["POST"], path: "/api/devices/ios/app-removal" },
  { id: "iosUsbProfileApply", domain: "devices", methods: ["POST"], path: "/api/devices/ios/usb-profile-apply" },
  { id: "iosMdmSettings", domain: "devices", methods: ["POST"], path: "/api/devices/ios/mdm/settings" },
  { id: "iosMdmDoctor", domain: "devices", methods: ["GET"], path: "/api/devices/ios/mdm/doctor" },
  { id: "iosMdmEnrollment", domain: "devices", methods: ["GET"], path: "/api/devices/ios/mdm/enrollment.mobileconfig" },
  { id: "iosMdmDeviceUsageToken", domain: "devices", methods: ["GET"], path: "/api/devices/ios/mdm/device-usage-token" },
  { id: "iosMdmQueuePolicy", domain: "devices", methods: ["POST"], path: "/api/devices/ios/mdm/queue-policy" },
  { id: "iosProfile", domain: "devices", methods: ["GET"], path: "/api/devices/ios/profile.mobileconfig" },
  { id: "deviceUsage", domain: "devices", methods: ["POST"], path: "/api/devices/usage" },
  { id: "grayscaleSettings", domain: "grayscale", methods: ["POST"], path: "/api/grayscale/settings" },
  { id: "grayscaleSchedule", domain: "grayscale", methods: ["POST"], path: "/api/grayscale/schedule" },
  { id: "grayscaleScheduleDelete", domain: "grayscale", methods: ["DELETE"], prefix: "/api/grayscale/schedule/" },
  { id: "intentionalGoal", domain: "intentionalUse", methods: ["POST"], path: "/api/intentional-use/goal" },
  { id: "intentionalAccountability", domain: "intentionalUse", methods: ["POST"], path: "/api/intentional-use/accountability" },
  { id: "intentionalRecoverySetup", domain: "intentionalUse", methods: ["POST"], path: "/api/intentional-use/recovery/setup" },
  { id: "intentionalRule", domain: "intentionalUse", methods: ["POST"], path: "/api/intentional-use/rule" },
  { id: "intentionalRuleDelete", domain: "intentionalUse", methods: ["DELETE"], prefix: "/api/intentional-use/rule/" },
  { id: "intentionalBehavior", domain: "intentionalUse", methods: ["POST"], path: "/api/intentional-use/behavior" },
  { id: "intentionalBehaviorDelete", domain: "intentionalUse", methods: ["DELETE"], prefix: "/api/intentional-use/behavior/" },
  { id: "intentionalBehaviorCheckIn", domain: "intentionalUse", methods: ["POST"], path: "/api/intentional-use/behavior/check-in" },
  { id: "intentionalJournalSecurity", domain: "intentionalUse", methods: ["GET"], path: "/api/intentional-use/journal/security" },
  { id: "intentionalJournalPassword", domain: "intentionalUse", methods: ["POST"], path: "/api/intentional-use/journal/password" },
  { id: "intentionalJournalUnlock", domain: "intentionalUse", methods: ["POST"], path: "/api/intentional-use/journal/unlock" },
  { id: "intentionalJournalTouchId", domain: "intentionalUse", methods: ["POST"], path: "/api/intentional-use/journal/unlock-touch-id" },
  { id: "intentionalJournalLock", domain: "intentionalUse", methods: ["POST"], path: "/api/intentional-use/journal/lock" },
  { id: "intentionalJournalEntries", domain: "intentionalUse", methods: ["GET"], path: "/api/intentional-use/journal/entries" },
  { id: "intentionalJournal", domain: "intentionalUse", methods: ["POST"], path: "/api/intentional-use/journal" },
  { id: "intentionalJournalDelete", domain: "intentionalUse", methods: ["DELETE"], prefix: "/api/intentional-use/journal/" },
  { id: "intentionalPlanList", domain: "intentionalUse", methods: ["POST"], path: "/api/intentional-use/plan/list" },
  { id: "intentionalPlanListDelete", domain: "intentionalUse", methods: ["DELETE"], prefix: "/api/intentional-use/plan/list/" },
  { id: "intentionalPlanItem", domain: "intentionalUse", methods: ["POST"], path: "/api/intentional-use/plan/item" },
  { id: "intentionalPlanItemDelete", domain: "intentionalUse", methods: ["DELETE"], prefix: "/api/intentional-use/plan/item/" },
  { id: "intentionalPlanBlock", domain: "intentionalUse", methods: ["POST"], path: "/api/intentional-use/plan/block" },
  { id: "intentionalPlanBlockDelete", domain: "intentionalUse", methods: ["DELETE"], prefix: "/api/intentional-use/plan/block/" },
  { id: "intentionalRecoveryCheckIn", domain: "intentionalUse", methods: ["POST"], path: "/api/intentional-use/recovery/check-in" },
  { id: "intentionalRecoverySos", domain: "intentionalUse", methods: ["POST"], path: "/api/intentional-use/recovery/sos" },
  { id: "intentionalPauseContinue", domain: "intentionalUse", methods: ["POST"], path: "/api/intentional-use/pause/continue" },
  { id: "intentionalPauseSkip", domain: "intentionalUse", methods: ["POST"], path: "/api/intentional-use/pause/skip" },
  { id: "profile", domain: "profiles", methods: ["POST"], path: "/api/profile" },
  { id: "profileDelete", domain: "profiles", methods: ["DELETE"], prefix: "/api/profile/" },
  { id: "sessionPreview", domain: "sessions", methods: ["POST"], path: "/api/session/preview" },
  { id: "sessionStart", domain: "sessions", methods: ["POST"], path: "/api/session/start" },
  { id: "sessionEnd", domain: "sessions", methods: ["POST"], path: "/api/session/end" },
  { id: "emergencyRequest", domain: "sessions", methods: ["POST"], path: "/api/emergency/request" },
  { id: "emergencyConfirm", domain: "sessions", methods: ["POST"], path: "/api/emergency/confirm" },
  { id: "schedule", domain: "schedules", methods: ["POST"], path: "/api/schedule" },
  { id: "limit", domain: "limits", methods: ["POST"], path: "/api/limit" },
  { id: "appLock", domain: "appLocks", methods: ["POST"], path: "/api/app-lock" },
  { id: "appLockDelete", domain: "appLocks", methods: ["DELETE"], prefix: "/api/app-lock/" },
  { id: "appLockUnlockRequest", domain: "appLocks", methods: ["POST"], path: "/api/app-lock/unlock/request" },
  { id: "appLockUnlockConfirm", domain: "appLocks", methods: ["POST"], path: "/api/app-lock/unlock/confirm" },
  { id: "maintenanceRequest", domain: "protection", methods: ["POST"], path: "/api/protection/maintenance/request" },
  { id: "maintenanceConfirm", domain: "protection", methods: ["POST"], path: "/api/protection/maintenance/confirm" },
  { id: "limitDelete", domain: "limits", methods: ["DELETE"], prefix: "/api/limit/" },
  { id: "scheduleDelete", domain: "schedules", methods: ["DELETE"], prefix: "/api/schedule/" }
]);

export function matchApiRoute(method: string, path: string) {
  return API_ROUTES.find((route) => {
    if (!route.methods.includes(method)) return false;
    if (route.path) return route.path === path;
    return route.prefix ? path.startsWith(route.prefix) : false;
  }) || null;
}

export function isExtensionApiPath(path: string): boolean {
  return API_ROUTES.some((route) => route.domain === "extension" && route.path === path);
}
