import assert from "node:assert/strict";
import { readFile, stat } from "node:fs/promises";
import { join } from "node:path";
import { distanceKeyQrMatrix } from "../../public/distance-key-qr.js";

function recordValue(value: unknown, label = "value"): Record<string, unknown> {
  assert.equal(typeof value, "object", `${label} should be an object`);
  assert.notEqual(value, null, `${label} should not be null`);
  return value as Record<string, unknown>;
}

function stringArrayValue(value: unknown, label = "value"): string[] {
  assert.ok(Array.isArray(value) && value.every((item) => typeof item === "string"), `${label} should be a string array`);
  return value as string[];
}

const root = process.cwd();
const sourceRoot = join(root, "..", "..");
const mainTsSource = await readFile(join(sourceRoot, "app", "main.ts"), "utf8");
const iosCheckpointSource = await readFile(join(sourceRoot, "scripts", "create-ios-layout-checkpoint.mjs"), "utf8");
const iosUsbApplySource = await readFile(join(sourceRoot, "scripts", "apply-ios-usb-profile.mjs"), "utf8");
const iosSupervisePreserveSource = await readFile(join(sourceRoot, "scripts", "supervise-ios-preserving-layout.mjs"), "utf8");
const apiRoutesTsSource = await readFile(join(sourceRoot, "src", "server", "apiRoutes.ts"), "utf8");
const deviceRoutesTsSource = await readFile(join(sourceRoot, "src", "server", "deviceRoutes.ts"), "utf8");
const appTsSource = await readFile(join(sourceRoot, "public", "app.ts"), "utf8");
const appModelTsSource = await readFile(join(sourceRoot, "public", "app-model.ts"), "utf8");
const appSource = await readFile(join(root, "public", "app.js"), "utf8");
const devicePanelSource = await readFile(join(root, "public", "device-panel.js"), "utf8");
const domSource = await readFile(join(root, "public", "dom.js"), "utf8");
const distanceKeyUiSource = await readFile(join(root, "public", "distance-key-ui.js"), "utf8");
const focusSoundSource = await readFile(join(root, "public", "focus-sound.js"), "utf8");
const formatSource = await readFile(join(root, "public", "format.js"), "utf8");
const hardeningPanelSource = await readFile(join(root, "public", "hardening-panel.js"), "utf8");
const qrSource = await readFile(join(root, "public", "distance-key-qr.js"), "utf8");
const monitorSource = await readFile(join(root, "src", "monitor.js"), "utf8");
const monitorPolicySource = await readFile(join(root, "src", "monitor", "policy.js"), "utf8");
const serverSource = await readFile(join(root, "src", "server.js"), "utf8");
const backupRoutesSource = await readFile(join(root, "src", "server", "backupRoutes.js"), "utf8");
const extensionApiSource = await readFile(join(root, "src", "server", "extensionApi.js"), "utf8");
const policyRoutesSource = await readFile(join(root, "src", "server", "policyRoutes.js"), "utf8");
const sessionRoutesSource = await readFile(join(root, "src", "server", "sessionRoutes.js"), "utf8");
const settingsRoutesSource = await readFile(join(root, "src", "server", "settingsRoutes.js"), "utf8");
const devServerSource = await readFile(join(root, "scripts", "dev-server.mjs"), "utf8");
const statePayloadSource = await readFile(join(root, "src", "server", "statePayload.js"), "utf8");
const packageJson = recordValue(JSON.parse(await readFile(join(root, "package.json"), "utf8")), "package.json");

assert.match(appSource, /from "\.\/api-client\.js"/);
assert.match(appSource, /from "\.\/device-targets\.js"/);
assert.match(appSource, /from "\.\/device-panel\.js"/);
assert.match(appSource, /from "\.\/distance-key-ui\.js"/);
assert.match(appSource, /from "\.\/dom\.js"/);
assert.match(appSource, /from "\.\/focus-sound\.js"/);
assert.match(appSource, /from "\.\/format\.js"/);
assert.match(appSource, /from "\.\/hardening-panel\.js"/);
assert.doesNotMatch(appSource, /innerHTML|insertAdjacentHTML|outerHTML|document\.write/);
assert.doesNotMatch(appSource, /function distanceKeyQrSvg|function distanceKeyQrMatrix|function qrReedSolomon/);
assert.doesNotMatch(appSource, /function createNoiseSource|async function parseResponse|function normalizeDistanceKeyScan/);
assert.doesNotMatch(appSource, /iosMdmForm|installLaunchAgent|applyHostsBlock/);
assert.match(appTsSource, /from "\.\/app-model\.js"/);
assert.match(appModelTsSource, /interface DashboardData/);
assert.match(mainTsSource, /function configureMenuBarResidency/);
assert.match(mainTsSource, /app\.dock\?\.hide\(\)/);
assert.match(mainTsSource, /app\.setLoginItemSettings\(/);
assert.match(mainTsSource, /wasOpenedAtLogin/);
assert.match(mainTsSource, /function shouldStayResident/);
assert.match(mainTsSource, /function hideVigilWindow/);
assert.doesNotMatch(mainTsSource, /label: "Quit Vigil"|role: "quit"/);
assert.match(devicePanelSource, /iosMdmForm/);
assert.match(domSource, /document\.createElement/);
assert.match(distanceKeyUiSource, /from "\.\/distance-key-qr\.js"/);
assert.match(distanceKeyUiSource, /function normalizeDistanceKeyScan/);
assert.match(focusSoundSource, /function createNoiseSource/);
assert.match(focusSoundSource, /function connectBinauralProfile/);
assert.match(focusSoundSource, /function connectIsochronicProfile/);
assert.match(focusSoundSource, /forest-lawn-creek\.ogg/);
assert.match(focusSoundSource, /bach-goldberg-aria/);
assert.match(focusSoundSource, /audioStartGeneration/);
assert.match(focusSoundSource, /function isCurrentStart/);
assert.doesNotMatch(focusSoundSource, /function createBaroqueSource/);
assert.ok((await stat(join(root, "public", "audio", "nature", "rain.ogg"))).size > 100_000);
assert.ok((await stat(join(root, "public", "audio", "nature", "ocean-waves.ogg"))).size > 1_000_000);
assert.ok((await stat(join(root, "public", "audio", "nature", "storm-thunderbolts.ogg"))).size > 1_000_000);
assert.ok((await stat(join(root, "public", "audio", "nature", "forest-lawn-creek.ogg"))).size > 1_000_000);
assert.ok((await stat(join(root, "public", "audio", "baroque", "bach-goldberg-aria-harpsichord.ogg"))).size > 1_000_000);
assert.ok((await stat(join(root, "public", "audio", "baroque", "handel-harmonious-blacksmith.ogg"))).size > 1_000_000);
assert.match(formatSource, /export function formatDuration/);
assert.match(hardeningPanelSource, /function renderHardening/);
assert.match(qrSource, /createElementNS/);
assert.match(monitorSource, /from "\.\/monitor\/policy\.js"/);
assert.match(monitorPolicySource, /function policyForSample/);

assert.doesNotMatch(serverSource, /function blockedPage|function hardeningAudit|async function runLocalScript|function sendJson/);
assert.match(serverSource, /from "\.\/server\/pages\.js"/);
assert.match(serverSource, /from "\.\/server\/http\.js"/);
assert.match(serverSource, /from "\.\/server\/localScripts\.js"/);
assert.match(serverSource, /from "\.\/server\/apiRoutes\.js"/);
assert.match(serverSource, /from "\.\/server\/backupRoutes\.js"/);
assert.match(serverSource, /from "\.\/server\/extensionApi\.js"/);
assert.match(serverSource, /from "\.\/server\/policyRoutes\.js"/);
assert.match(serverSource, /from "\.\/server\/sessionRoutes\.js"/);
assert.match(serverSource, /from "\.\/server\/settingsRoutes\.js"/);
assert.match(serverSource, /from "\.\/server\/statePayload\.js"/);
assert.doesNotMatch(serverSource, /function handleExtensionCheck|function handleExtensionRulesSync/);
assert.match(extensionApiSource, /function handleExtensionCheck/);
assert.match(policyRoutesSource, /function handlePolicyApiRoute/);
assert.match(sessionRoutesSource, /function handleSessionApiRoute/);
assert.match(settingsRoutesSource, /SETTING_MUTATIONS/);
assert.match(statePayloadSource, /from "\.\/hardeningSummary\.js"/);
assert.match(backupRoutesSource, /function redactSensitiveFields/);
assert.match(backupRoutesSource, /restore[\s\S]*supported: false/);

const build = recordValue(packageJson.build, "package build");
const macBuild = recordValue(build.mac, "mac build");
const macExtendInfo = recordValue(macBuild.extendInfo, "mac extendInfo");
const scripts = recordValue(packageJson.scripts, "package scripts");
assert.match(String(scripts.dev), /--watch-path=src/);
assert.match(String(scripts.dev), /dist\/runtime\/scripts\/dev-server\.mjs/);
assert.match(String(scripts["ios:checkpoint"]), /create-ios-layout-checkpoint\.mjs/);
assert.match(String(scripts["ios:supervise-preserve-layout"]), /supervise-ios-preserving-layout\.mjs/);
assert.match(String(scripts["ios:apply-usb"]), /apply-ios-usb-profile\.mjs/);
assert.match(iosCheckpointSource, /ios-checkpoints/);
assert.match(iosCheckpointSource, /SpringBoard\/Home Screen layout records/);
assert.match(iosCheckpointSource, /Manifest\.db/);
assert.match(iosCheckpointSource, /"usbmux", "list", "--usb"/);
assert.match(iosCheckpointSource, /resolveUsbDevice\(options\.udid\)/);
assert.match(iosUsbApplySource, /--require-checkpoint/);
assert.match(iosUsbApplySource, /--supervisor-keybag/);
assert.match(iosUsbApplySource, /VIGIL_SUPERVISOR_KEYBAG/);
assert.match(iosUsbApplySource, /readLayoutPaths\(manifestPath\)/);
assert.match(iosUsbApplySource, /SpringBoard\/Home Screen layout records/);
assert.match(iosUsbApplySource, /\/api\/devices\/ios\/usb-profile-apply/);
assert.match(iosUsbApplySource, /partial-restore\/no-erase supervision trick/);
assert.match(iosUsbApplySource, /"usbmux", "list", "--usb"/);
assert.match(iosUsbApplySource, /resolveUsbDevice\(options\.udid\)/);
assert.match(iosUsbApplySource, /state\?\.state\?\.deviceControls\?\.ios/);
assert.doesNotMatch(iosUsbApplySource, /create-keybag/);
assert.doesNotMatch(iosUsbApplySource, /\/api\/devices\/ios\/settings/);
assert.doesNotMatch(iosUsbApplySource, /["']supervise["']/);
assert.match(iosSupervisePreserveSource, /--yes-supervise-and-restore/);
assert.match(iosSupervisePreserveSource, /backup2",\s*"backup"/);
assert.match(iosSupervisePreserveSource, /"--full"/);
assert.match(iosSupervisePreserveSource, /profile",\s*"create-keybag"/);
assert.match(iosSupervisePreserveSource, /profile",\s*"supervise"/);
assert.match(iosSupervisePreserveSource, /backup2",\s*"restore"/);
assert.match(iosSupervisePreserveSource, /"--system"/);
assert.match(iosSupervisePreserveSource, /"--settings"/);
assert.match(iosSupervisePreserveSource, /"--remove"/);
assert.match(iosSupervisePreserveSource, /apply-ios-usb-profile\.mjs/);
assert.match(iosSupervisePreserveSource, /--require-checkpoint/);
assert.match(iosSupervisePreserveSource, /isSupervisedCloud\(restoredCloud\)/);
assert.match(iosSupervisePreserveSource, /SpringBoard\/Home Screen layout records/);
assert.match(apiRoutesTsSource, /iosUsbProfileApply/);
assert.match(deviceRoutesTsSource, /ios_usb_profile_apply_prepared/);
assert.match(String(scripts["build:mac"]), /-c\.mac\.identity=null/);
assert.match(String(scripts["dist:mac"]), /-c\.mac\.identity=null/);
assert.doesNotMatch(String(scripts["build:mac:signed"]), /identity=null/);
assert.doesNotMatch(String(scripts["dist:mac:signed"]), /identity=null/);
assert.match(devServerSource, /npm", \["run", "build"\]/);
assert.equal(build.asar, true);
assert.equal(macBuild.identity, undefined);
assert.equal(macExtendInfo.LSUIElement, true);
assert.ok(stringArrayValue(build.files, "build files").includes("dist/runtime/**/*"));
assert.ok(stringArrayValue(build.asarUnpack, "asar unpack").includes("dist/runtime/package.json"));
assert.ok(stringArrayValue(build.asarUnpack, "asar unpack").includes("dist/runtime/public/**/*"));
assert.ok(stringArrayValue(build.asarUnpack, "asar unpack").includes("dist/runtime/src/**/*"));
assert.ok(stringArrayValue(build.asarUnpack, "asar unpack").includes("dist/runtime/scripts/**/*"));
assert.ok(stringArrayValue(build.asarUnpack, "asar unpack").includes("dist/runtime/extension/**/*"));

const matrix = distanceKeyQrMatrix("ABCD-EFGH-1234");
assert.equal(matrix.length, 21);
assert.equal(matrix.every((row) => row.length === 21), true);
assert.equal(matrix.flat().every((value) => typeof value === "boolean"), true);
assert.throws(() => distanceKeyQrMatrix("emoji-😀"), /cannot be encoded/);
